name: "Push to Deta Space"
description: "A GitHub Action to push to Space"

inputs:
  space-access-token:
    description: "Space access token"
    required: true
  space-project-id:
    description: "ID of the project to push to"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      shell: bash
      run: |
        go mod init space-deploy
        wget https://raw.githubusercontent.com/neobrains/space-push/master/deploy.go
        go build deploy.go

    - name: Push to Space
      shell: script -q -e -c "bash {0}"
      run: |
        export SPACE_ACCESS_TOKEN=${{ inputs.space-access-token }}
        export SPACE_PROJECT_ID=${{ inputs.space-project-id }}
        ./deploy

branding:
  icon: git-commit
  color: purple
